import { useState } from 'react';
import type { RoomSnapshot } from '../../types/room';

export function TicTacToe({state,seat,busy,onMove,onRematch}:{state:Record<string,unknown>;seat:number;busy:boolean;onMove:(cell:number)=>void;onRematch:()=>void}){
  const board=Array.isArray(state.board)?state.board as (string|null)[]:[];const winner=state.winner;const turn=Number(state.turn_seat)===seat;
  return <div className="mini-game"><div className="notice warm">{winner?`Ronde selesai: ${String(winner)}`:turn?'Giliranmu, pilih satu kotak ✨':'Giliran pasanganmu…'}</div><div className="ttt-board">{board.map((cell,index)=><button className="ttt-cell" key={index} disabled={!!winner||!turn||busy||!!cell} onClick={()=>onMove(index)}>{cell||'·'}</button>)}</div>{winner?<button className="button primary" onClick={onRematch} disabled={busy}>Main ulang 🔁</button>:null}</div>;
}

export function SnakesBoard({state,mySeat,userId,members,onRoll,onPunishment,busy}:{state:Record<string,unknown>;mySeat:number;userId:string;members:RoomSnapshot['members'];onRoll:()=>void;onPunishment:(answer:string)=>void;busy:boolean}){
  const [answer,setAnswer]=useState('');const positions=state.positions as Record<string,number>|undefined;const myMember=members.find((member)=>member.seat===mySeat);const mine=myMember?positions?.[myMember.id]||1:1;const turn=Number(state.turn_seat)===mySeat;const punishment=state.punishment as {status?:string;user_id?:string;prompt?:string;from?:number;to?:number}|null;const myTurnPunishment=punishment?.status==='active'&&punishment.user_id===userId;
  return <div className="mini-game"><div className="snake-summary"><span>🐍 {mine} / 100</span><span>🎲 {String(state.last_roll||'—')}</span><span>Giliran {turn?'kamu':'pasangan'}</span></div><div className="snake-track">{Array.from({length:100},(_,index)=>{const cell=100-index;const occupant=Object.entries(positions||{}).find(([,position])=>position===cell);const player=members.find((member)=>member.id===occupant?.[0]);return <div className={`snake-cell ${cell%10===0?'milestone':''}`} key={cell}><small>{cell}</small>{player&&<span title={player.name}>{player.avatar}</span>}</div>})}</div>{myTurnPunishment?<><div className="notice warm">🐍 {punishment.prompt} ({punishment.from} → {punishment.to})</div><div className="composer"><input className="field" value={answer} maxLength={500} onChange={(event)=>setAnswer(event.target.value)} placeholder="Jawab singkat dulu ya…"/><button className="button primary" disabled={!answer.trim()||busy} onClick={()=>{onPunishment(answer.trim());setAnswer('')}}>Selesai</button></div></>:punishment?.status==='active'?<div className="notice warm">Pasanganmu lagi menyelesaikan tantangan kecil…</div>:state.winner?<div className="notice success">Pemenangnya mencapai kotak 100! 🏆</div>:<button className="button primary" onClick={onRoll} disabled={!turn||busy}>{busy?'Dadu berputar…':turn?'🎲 Lempar dadu':'Tunggu giliran'}</button>}<small>Dadu dan posisi disimpan oleh database.</small></div>;
}
